image: docker.elastic.co/beats/filebeat-oss

daemonset:
  extraEnvs:
    - name: "ELASTICSEARCH_USERNAME"
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: username
    - name: "ELASTICSEARCH_PASSWORD"
      valueFrom:
        secretKeyRef:
          name: elastic-credentials
          key: password
  resources:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "100m"
      memory: "200Mi"
  
  filebeatConfig:
    filebeat.yml: |
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: ["http://elasticsearch-master:9200"]
        username: '${ELASTICSEARCH_USERNAME}'
        password: '${ELASTICSEARCH_PASSWORD}'
        index: "k8s-test-%{[agent.version]}-%{[kubernetes.namespace]}-%{+yyyy.MM.dd}"
      setup.ilm.enabled: false
      setup.template.enabled: true
      setup.template.name: "k8s-test-%{[agent.version]}"
      setup.template.pattern: "k8s-test-%{[agent.version]}-*"
      setup.template.overwrite: false
      setup.template.settings:
        index.number_of_shards: 3
        index.number_of_replicas: 0
      monitoring:
        enabled: true
        elasticsearch:
          hosts: ["http://elasticsearch-master:9200"]
          username: "${ELASTICSEARCH_USERNAME}"
          password: "${ELASTICSEARCH_PASSWORD}"
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            namespace: webservice
            resource: pod
            scope: cluster
            add_resource_metadata:
              namespace:
                enabled: false
                include_labels: []
              node:
                enabled: false
                include_labels: []
                include_annotations: []
            templates:
               - config:
                  - type: container
                    paths:
                      - /var/log/containers/*-${data.kubernetes.container.id}.log
#                condition:
#                  not:
#                    equals:
#                      kubernetes.container.name: webservice