elasticsearchHosts: "http://elasticsearch-master:9200"

extraEnvs:
#  - name: "NODE_OPTIONS"
#    value: "--max-old-space-size=1800"
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "200m"
    memory: "1Gi"

# INGRESS:
ingress:
  enabled: true
  hosts:
    - host: kibana.local
      paths:
        - path: /

kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: http://kibana.local