image: docker.elastic.co/apm/apm-server-oss

replicas: 1
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
    queue: {}
    output.file:
      enabled: false
    output.elasticsearch:
      hosts: ["http://elasticsearch-master:9200"]
      index: "apm-oss-%{[observer.version]}-%{+yyyy.MM.dd}"
      username: "${ELASTICSEARCH_USERNAME}"
      password: "${ELASTICSEARCH_PASSWORD}"
      worker: 2
      timeout: 30
    setup.template.name: "apm-server"
    setup.template.pattern: "apm-oss-*"
    auth:
      secret_token: 123456
    anonymous:
      enabled: false
    ssl:
      enabled: false

extraEnvs:
  - name: "ELASTICSEARCH_USERNAME"
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username
  - name: "ELASTICSEARCH_PASSWORD"
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  averageCpuUtilization: 50

ingress:
  enabled: true
  path: /
  hosts:
    - apm-server.local
